<div class="alert alert-success">
    <strong>Excelente!</strong> No hay errores en el formulario:<br><br>
    <ul>
        <li>Hemos recibido su mensaje, luego nos pondremos en contacto, gracias!</li>
    </ul>
</div>
<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->titulo ?></div>
            <div class="panel-body">
                <table class="table table-striped table-hover" style="width:900px; text-align:left">
                    <tbody>
                        <tr>          
                            <td><?= $this->formLabel($this->form->get('nombre')) ?></td>
                            <td><?php echo $contacto['nombre'] ?></td>
                        </tr>
                        <tr>          
                            <td><?= $this->formLabel($this->form->get('genero')) ?></td>
                            <td><?php echo $contacto['genero'] ?></td>
                        </tr>
                        <tr>          
                            <td><?= $this->formLabel($this->form->get('email')) ?></td>
                            <td><?php echo $contacto['email'] ?></td>
                        </tr>
                        <tr>          
                            <td><?= $this->formLabel($this->form->get('area')) ?></td>
                            <td><?php echo $contacto['area'] ?></td>
                        </tr>
                        <tr>          
                            <td><?= $this->formLabel($this->form->get('tema')) ?></td>
                            <td><?php echo $contacto['tema'] ?></td>
                        </tr>
                        <tr>          
                            <td><?= $this->formLabel($this->form->get('mensaje')) ?></td>
                            <td><?php echo $contacto['mensaje'] ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
