<?php
$this->form->prepare();
$this->form->setAttribute('action', $this->url('usuario', ['action' => 'registrar']))
        ->setAttribute('method', 'post')
        ->setAttribute('class', 'form-horizontal')
        ->setAttribute('role', 'form');
?>
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">

        
        
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->titulo ?></h3>
            </div>
            <div class="panel-body">
                <p><a class="btn btn-default btn-xs" href="<?php echo $this->url('usuario', ['action' => 'listar',]) ?>">volver</a></p>
                <?= $this->form()->openTag($this->form); ?>
                <div class="form-group <?= (!empty($this->form->get('nombre')->getMessages())) ? 'has-error' : '' ?>">
                    <?= $this->formLabel($this->form->get('nombre')) ?>
                    <div class="col-sm-5">
                        <?= $this->formInput($this->form->get('nombre')) ?>
                    </div>
                    <div style="color: red"><?= $this->formElementErrors($this->form->get('nombre')) ?></div>
                </div>

                <div class="form-group <?= (!empty($this->form->get('apellido')->getMessages())) ? 'has-error' : '' ?>">
                    <?= $this->formLabel($this->form->get('apellido')) ?>
                    <div class="col-sm-5">
                        <?= $this->formInput($this->form->get('apellido')) ?>
                    </div>
                    <div style="color: red"><?= $this->formElementErrors($this->form->get('apellido')) ?></div>
                </div>

                <div class="form-group <?= (!empty($this->form->get('email')->getMessages())) ? 'has-error' : '' ?>">
                    <?= $this->formLabel($this->form->get('email')) ?>
                    <div class="col-sm-5">
                        <?= $this->formEmail($this->form->get('email')) ?>
                    </div>
                    <div style="color: red"><?= $this->formElementErrors($this->form->get('email')) ?></div>
                </div>

                <div class="form-group <?= (!empty($this->form->get('password')->getMessages())) ? 'has-error' : '' ?>">
                    <?= $this->formLabel($this->form->get('password')) ?>
                    <div class="col-sm-5">
                        <?= $this->formPassword($this->form->get('password')) ?>
                    </div>
                    <div style="color: red"><?= $this->formElementErrors($this->form->get('password')) ?></div>
                </div>
                
                <div class="form-group <?= (!empty($this->form->get('confirmarPassword')->getMessages())) ? 'has-error' : '' ?>">
                    <?= $this->formLabel($this->form->get('confirmarPassword')) ?>
                    <div class="col-sm-5">
                        <?= $this->formPassword($this->form->get('confirmarPassword')) ?>
                    </div>
                    <div style="color: red"><?= $this->formElementErrors($this->form->get('confirmarPassword')) ?></div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-5">
                        <?= $this->formSubmit($form->get('send')) ?>
                    </div>
                </div>
                <?= $this->formHidden($form->get('id')) ?>
                <?= $this->form()->closeTag() ?>

            </div>
        </div>
    </div>
</div>